DROP TABLE XP_SCHD CASCADE CONSTRAINTS;
DROP TABLE XP_USER CASCADE CONSTRAINTS;
DROP TABLE XP_DEPT CASCADE CONSTRAINTS;
DROP TABLE XP_ATTACHED CASCADE CONSTRAINTS;
DROP TABLE XP_BOARD CASCADE CONSTRAINTS;
DROP TABLE XP_COMMUNITY CASCADE CONSTRAINTS;
DROP TABLE XP_CATEGORY CASCADE CONSTRAINTS;

DROP SEQUENCE XP_CATEGORY_ID_SEQ;
DROP SEQUENCE XP_COMMUNITY_ID_SEQ;
DROP SEQUENCE XP_POST_ID_SEQ;
DROP SEQUENCE XP_USER_ID_SEQ;
DROP SEQUENCE XP_SCHD_ID_SEQ;
DROP SEQUENCE XP_FILE_ID_SEQ;