DROP TABLE XP_SCHD IF EXISTS CASCADE;
DROP TABLE XP_USER IF EXISTS CASCADE;
DROP TABLE XP_DEPT IF EXISTS CASCADE;
DROP TABLE XP_ATTACHED IF EXISTS CASCADE;
DROP TABLE XP_BOARD IF EXISTS CASCADE;
DROP TABLE XP_COMMUNITY IF EXISTS CASCADE;
DROP TABLE XP_CATEGORY IF EXISTS CASCADE;
DROP TABLE XP_MOVIE IF EXISTS CASCADE;
DROP TABLE XP_GENRE IF EXISTS CASCADE;

DROP SEQUENCE XP_CATEGORY_ID_SEQ;
DROP SEQUENCE XP_COMMUNITY_ID_SEQ;
DROP SEQUENCE XP_POST_ID_SEQ;
DROP SEQUENCE XP_USER_ID_SEQ;
DROP SEQUENCE XP_SCHD_ID_SEQ;
DROP SEQUENCE XP_FILE_ID_SEQ;