DROP TABLE XP_SCHD;
DROP TABLE XP_USER;
DROP TABLE XP_DEPT;
DROP TABLE XP_ATTACHED;
DROP TABLE XP_BOARD;
DROP TABLE XP_COMMUNITY;
DROP TABLE XP_CATEGORY;

DROP SEQUENCE XP_CATEGORY_ID_SEQ;
DROP SEQUENCE XP_COMMUNITY_ID_SEQ;
DROP SEQUENCE XP_POST_ID_SEQ;
DROP SEQUENCE XP_USER_ID_SEQ;
DROP SEQUENCE XP_SCHD_ID_SEQ;
DROP SEQUENCE XP_FILE_ID_SEQ;