DROP TABLE IF EXISTS XP_SCHD;
DROP TABLE IF EXISTS XP_USER;
DROP TABLE IF EXISTS XP_DEPT;
DROP TABLE IF EXISTS XP_ATTACHED;
DROP TABLE IF EXISTS XP_BOARD;
DROP TABLE IF EXISTS XP_COMMUNITY;
DROP TABLE IF EXISTS XP_CATEGORY;

DROP TABLE IF EXISTS MYSQL_XP_SEQ;
--DROP FUNCTION IF EXISTS XP_CATEGORY_ID_SEQ_NEXT_VALUE;
--DROP FUNCTION IF EXISTS XP_COMMUNITY_ID_SEQ_NEXT_VALUE;
--DROP FUNCTION IF EXISTS XP_POST_ID_SEQ_NEXT_VALUE;
--DROP FUNCTION IF EXISTS XP_USER_ID_SEQ_NEXT_VALUE;
--DROP FUNCTION IF EXISTS XP_SCHD_ID_SEQ_NEXT_VALUE;
--DROP FUNCTION IF EXISTS XP_FILE_ID_SEQ_NEXT_VALUE;