DROP TABLE JQUERY_MOVIE;
DROP TABLE JQUERY_GENRE;
DROP TABLE JQUERY_IDS;

DROP TABLE JQUERY_USER;
DROP TABLE JQUERY_DEPT;
DROP TABLE JQUERY_BOARD;
DROP TABLE JQUERY_COMMUNITY;
DROP TABLE JQUERY_CATEGORY;