/*
 * Copyright 2008-2012 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.anyframe.hibernate.sample.model.bidirection;

// Generated 2008. 9. 1 ���� 1:00:42 by Hibernate Tools 3.2.1.GA

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Movie generated by hbm2java
 */
public class Movie implements Serializable {

	private static final long serialVersionUID = 1L;
	private String movieId;
	private Country country;
	private String title;
	private String director;
	private Date releaseDate;
	private Integer rank;

	private Set<Category> categories = new HashSet<Category>(0);

	// add some attributes for selecting result
	private String categoryName;
	private String countryName;

	public Movie() {
	}

	public Movie(String movieId, String title, String director) {
		this.movieId = movieId;
		this.title = title;
		this.director = director;
	}

	public Movie(String movieId, Country country, String title,
			String director, Date releaseDate, Set<Category> categories) {
		this.movieId = movieId;
		this.country = country;
		this.title = title;
		this.director = director;
		this.releaseDate = releaseDate;
		this.categories = categories;
	}

	public Movie(String movieId, String title, String director,
			String categoryName, String countryName) {
		this.movieId = movieId;
		this.title = title;
		this.director = director;
		this.categoryName = categoryName;
		this.countryName = countryName;
	}

	public String getMovieId() {
		return this.movieId;
	}

	public void setMovieId(String movieId) {
		this.movieId = movieId;
	}

	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDirector() {
		return this.director;
	}

	public void setDirector(String director) {
		this.director = director;
	}

	public Date getReleaseDate() {
		return this.releaseDate;
	}

	public void setReleaseDate(Date releaseDate) {
		this.releaseDate = releaseDate;
	}

	public Set<Category> getCategories() {
		return this.categories;
	}

	public void setCategories(Set<Category> categories) {
		this.categories = categories;
	}

	public String getCategoryName() {
		return categoryName;
	}

	public String getCountryName() {
		return countryName;
	}

	public Integer getRank() {
		return rank;
	}

	public void setRank(Integer rank) {
		this.rank = rank;
	}
}
