DROP TABLE MIP_SCHD CASCADE CONSTRAINTS;
DROP TABLE MIP_USER CASCADE CONSTRAINTS;
DROP TABLE MIP_DEPT CASCADE CONSTRAINTS;
DROP TABLE MIP_ATTACHED CASCADE CONSTRAINTS;
DROP TABLE MIP_BOARD CASCADE CONSTRAINTS;
DROP TABLE MIP_COMMUNITY CASCADE CONSTRAINTS;
DROP TABLE MIP_CATEGORY CASCADE CONSTRAINTS;

DROP SEQUENCE CATEGORY_ID_SEQ;
DROP SEQUENCE COMMUNITY_ID_SEQ;
DROP SEQUENCE POST_ID_SEQ;
DROP SEQUENCE USER_ID_SEQ;
DROP SEQUENCE SCHD_ID_SEQ;
DROP SEQUENCE FILE_ID_SEQ;