DROP TABLE MIP_SCHD;
DROP TABLE MIP_USER;
DROP TABLE MIP_DEPT;
DROP TABLE MIP_ATTACHED;
DROP TABLE MIP_BOARD;
DROP TABLE MIP_COMMUNITY;
DROP TABLE MIP_CATEGORY;

DROP SEQUENCE CATEGORY_ID_SEQ;
DROP SEQUENCE COMMUNITY_ID_SEQ;
DROP SEQUENCE POST_ID_SEQ;
DROP SEQUENCE USER_ID_SEQ;
DROP SEQUENCE SCHD_ID_SEQ;
DROP SEQUENCE FILE_ID_SEQ;

commit;