DROP TABLE MIP_SCHD IF EXISTS CASCADE;
DROP TABLE MIP_USER IF EXISTS CASCADE;
DROP TABLE MIP_DEPT IF EXISTS CASCADE;
DROP TABLE MIP_ATTACHED IF EXISTS CASCADE;
DROP TABLE MIP_BOARD IF EXISTS CASCADE;
DROP TABLE MIP_COMMUNITY IF EXISTS CASCADE;
DROP TABLE MIP_CATEGORY IF EXISTS CASCADE;
DROP TABLE MIP_MOVIE IF EXISTS CASCADE;
DROP TABLE MIP_GENRE IF EXISTS CASCADE;

DROP SEQUENCE CATEGORY_ID_SEQ;
DROP SEQUENCE COMMUNITY_ID_SEQ;
DROP SEQUENCE POST_ID_SEQ;
DROP SEQUENCE USER_ID_SEQ;
DROP SEQUENCE SCHD_ID_SEQ;
DROP SEQUENCE FILE_ID_SEQ;