DROP TABLE IF EXISTS MIP_SCHD;
DROP TABLE IF EXISTS MIP_USER;
DROP TABLE IF EXISTS MIP_DEPT;
DROP TABLE IF EXISTS MIP_ATTACHED;
DROP TABLE IF EXISTS MIP_BOARD;
DROP TABLE IF EXISTS MIP_COMMUNITY;
DROP TABLE IF EXISTS MIP_CATEGORY;

DROP TABLE IF EXISTS MYSQL_MIP_SEQ;
--DROP FUNCTION IF EXISTS CATEGORY_ID_SEQ_NEXT_VALUE;
--DROP FUNCTION IF EXISTS COMMUNITY_ID_SEQ_NEXT_VALUE;
--DROP FUNCTION IF EXISTS POST_ID_SEQ_NEXT_VALUE;
--DROP FUNCTION IF EXISTS USER_ID_SEQ_NEXT_VALUE;
--DROP FUNCTION IF EXISTS SCHD_ID_SEQ_NEXT_VALUE;
--DROP FUNCTION IF EXISTS FILE_ID_SEQ_NEXT_VALUE;