package org.anyframe.sample.hibernate.model.unidirection;

// Generated 2008. 9. 1 ���� 1:00:42 by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * Movie generated by hbm2java
 */
public class Movie implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;

	private String movieId;
	private String countryCode;
	private String title;
	private String director;
	private Date releaseDate;

	public Movie() {
	}

	public Movie(String movieId, String title, String director) {
		this.movieId = movieId;
		this.title = title;
		this.director = director;
	}

	public Movie(String movieId, String countryCode, String title,
			String director, Date releaseDate) {
		this.movieId = movieId;
		this.countryCode = countryCode;
		this.title = title;
		this.director = director;
		this.releaseDate = releaseDate;
	}

	public String getMovieId() {
		return this.movieId;
	}

	public void setMovieId(String movieId) {
		this.movieId = movieId;
	}

	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDirector() {
		return this.director;
	}

	public void setDirector(String director) {
		this.director = director;
	}

	public Date getReleaseDate() {
		return this.releaseDate;
	}

	public void setReleaseDate(Date releaseDate) {
		this.releaseDate = releaseDate;
	}
}
