DROP TABLE JQUERY_MOVIE CASCADE CONSTRAINTS;
DROP TABLE JQUERY_GENRE CASCADE CONSTRAINTS;
DROP TABLE JQUERY_IDS CASCADE CONSTRAINTS;

DROP TABLE JQUERY_USER CASCADE CONSTRAINTS;
DROP TABLE JQUERY_DEPT CASCADE CONSTRAINTS;
DROP TABLE JQUERY_BOARD CASCADE CONSTRAINTS;
DROP TABLE JQUERY_COMMUNITY CASCADE CONSTRAINTS;
DROP TABLE JQUERY_CATEGORY CASCADE CONSTRAINTS;

DROP SEQUENCE JQUERY_CATEGORY_ID_SEQ;
DROP SEQUENCE JQUERY_COMMUNITY_ID_SEQ;
DROP SEQUENCE JQUERY_POST_ID_SEQ;
DROP SEQUENCE JQUERY_USER_ID_SEQ;
DROP SEQUENCE JQUERY_FILE_ID_SEQ;