DROP TABLE JQUERY_MOVIE;
DROP TABLE JQUERY_GENRE;
DROP TABLE JQUERY_IDS;

DROP TABLE IF EXISTS JQUERY_USER;
DROP TABLE IF EXISTS JQUERY_DEPT;
DROP TABLE IF EXISTS JQUERY_BOARD;
DROP TABLE IF EXISTS JQUERY_COMMUNITY;
DROP TABLE IF EXISTS JQUERY_CATEGORY;

DROP TABLE IF EXISTS MYSQL_JQUERY_SEQ;