CREATE TABLE SCHEDULING_JOB(
	JOB_NAME VARCHAR2(100) NOT NULL, 
	GROUP_NAME VARCHAR2(100) NOT NULL, 
	TARGET_CLASS VARCHAR2(200) NOT NULL, 
	TARGET_METHOD VARCHAR2(100), 
	SCHEDULE VARCHAR2(30) NOT NULL, 
	SCHEDULE_TYPE VARCHAR2(10) NOT NULL, 
	START_DATE VARCHAR2(30) NOT NULL, 
	END_DATE VARCHAR2(30), 
	DESCRIPTION VARCHAR2(4000), 
	CONSTRAINT PK_SCHEDULING_JOB PRIMARY KEY(JOB_NAME, GROUP_NAME)
);

commit;