CREATE TABLE SCHEDULING_JOB(
	JOB_NAME VARCHAR(100) NOT NULL, 
	GROUP_NAME VARCHAR(100) NOT NULL, 
	TARGET_CLASS VARCHAR(200) NOT NULL, 
	TARGET_METHOD VARCHAR(100) NULL, 
	SCHEDULE VARCHAR(30) NOT NULL, 
	SCHEDULE_TYPE VARCHAR(10) NOT NULL, 
	START_DATE VARCHAR(30) NOT NULL, 
	END_DATE VARCHAR(30) NULL, 
	DESCRIPTION VARCHAR(4000) NULL, 
	CONSTRAINT PK_SCHEDULING_JOB PRIMARY KEY(JOB_NAME, GROUP_NAME)
);

commit;