DROP TABLE JQUERY_MOVIE IF EXISTS CASCADE;
DROP TABLE JQUERY_GENRE IF EXISTS CASCADE;
DROP TABLE JQUERY_IDS IF EXISTS CASCADE;

DROP TABLE JQUERY_CATEGORY IF EXISTS CASCADE;
DROP TABLE JQUERY_COMMUNITY IF EXISTS CASCADE;
DROP TABLE JQUERY_BOARD IF EXISTS CASCADE;
DROP TABLE JQUERY_DEPT IF EXISTS CASCADE;
DROP TABLE JQUERY_USER IF EXISTS CASCADE;

DROP SEQUENCE JQUERY_FILE_ID_SEQ;