DROP TABLE IF EXISTS FLEX_BOARD;
DROP TABLE IF EXISTS FLEX_CATEGORY;
DROP TABLE IF EXISTS FLEX_COMMUNITY;
DROP TABLE IF EXISTS FLEX_DEPT;
DROP TABLE IF EXISTS FLEX_USER;
DROP TABLE IF EXISTS FLEX_MOVIE;
DROP TABLE IF EXISTS FLEX_GENRE;
DROP TABLE IF EXISTS FLEX_ATTACHED;
DROP TABLE IF EXISTS FLEX_INDUSTRY;
DROP TABLE IF EXISTS FLEX_COMPANY;
DROP TABLE IF EXISTS FLEX_PRODUCT;
DROP TABLE IF EXISTS FLEX_CONTACT;

DROP TABLE IF EXISTS MYSQL_SEQ;
--DROP FUNCTION IF EXISTS FLEX_CATEGORY_ID_SEQ_NEXT_VALUE;
--DROP FUNCTION IF EXISTS FLEX_COMMUNITY_ID_SEQ_NEXT_VALUE;
--DROP FUNCTION IF EXISTS FLEX_POST_ID_SEQ_NEXT_VALUE;
--DROP FUNCTION IF EXISTS FLEX_USER_ID_SEQ_NEXT_VALUE;