DROP TABLE FLEX_BOARD;
DROP TABLE FLEX_CATEGORY;
DROP TABLE FLEX_COMMUNITY;
DROP TABLE FLEX_DEPT;
DROP TABLE FLEX_USER;

DROP SEQUENCE FLEX_CATEGORY_ID_SEQ;
DROP SEQUENCE FLEX_COMMUNITY_ID_SEQ;
DROP SEQUENCE FLEX_POST_ID_SEQ;
DROP SEQUENCE FLEX_USER_ID_SEQ;

commit;