DROP TABLE FLEX_BOARD CASCADE CONSTRAINTS;
DROP TABLE FLEX_CATEGORY CASCADE CONSTRAINTS;
DROP TABLE FLEX_COMMUNITY CASCADE CONSTRAINTS;
DROP TABLE FLEX_DEPT CASCADE CONSTRAINTS;
DROP TABLE FLEX_USER CASCADE CONSTRAINTS;

DROP SEQUENCE FLEX_CATEGORY_ID_SEQ;
DROP SEQUENCE FLEX_COMMUNITY_ID_SEQ;
DROP SEQUENCE FLEX_POST_ID_SEQ;
DROP SEQUENCE FLEX_USER_ID_SEQ;
