DROP TABLE IF EXISTS FLEX_BOARD;
DROP TABLE IF EXISTS FLEX_CATEGORY;
DROP TABLE IF EXISTS FLEX_COMMUNITY;
DROP TABLE IF EXISTS FLEX_DEPT;
DROP TABLE IF EXISTS FLEX_USER;

DROP TABLE IF EXISTS MYSQL_SEQ;
--DROP FUNCTION IF EXISTS FLEX_CATEGORY_ID_SEQ_NEXT_VALUE;
--DROP FUNCTION IF EXISTS FLEX_COMMUNITY_ID_SEQ_NEXT_VALUE;
--DROP FUNCTION IF EXISTS FLEX_POST_ID_SEQ_NEXT_VALUE;
--DROP FUNCTION IF EXISTS FLEX_USER_ID_SEQ_NEXT_VALUE;