DROP TABLE FLEX_BOARD IF EXISTS CASCADE;
DROP TABLE FLEX_CATEGORY IF EXISTS CASCADE;
DROP TABLE FLEX_COMMUNITY IF EXISTS CASCADE;
DROP TABLE FLEX_DEPT IF EXISTS CASCADE;
DROP TABLE FLEX_USER IF EXISTS CASCADE;

DROP SEQUENCE FLEX_CATEGORY_ID_SEQ;
DROP SEQUENCE FLEX_COMMUNITY_ID_SEQ;
DROP SEQUENCE FLEX_POST_ID_SEQ;
DROP SEQUENCE FLEX_USER_ID_SEQ;