DROP TABLE FLEX_BOARD;
DROP TABLE FLEX_CATEGORY;
DROP TABLE FLEX_COMMUNITY;
DROP TABLE FLEX_DEPT;
DROP TABLE FLEX_USER;
DROP TABLE FLEX_MOVIE;
DROP TABLE FLEX_GENRE;
DROP TABLE FLEX_ATTACHED;
DROP TABLE FLEX_INDUSTRY;
DROP TABLE FLEX_COMPANY;
DROP TABLE FLEX_PRODUCT;
DROP TABLE FLEX_CONTACT;

DROP SEQUENCE FLEX_CATEGORY_ID_SEQ;
DROP SEQUENCE FLEX_COMMUNITY_ID_SEQ;
DROP SEQUENCE FLEX_POST_ID_SEQ;
DROP SEQUENCE FLEX_USER_ID_SEQ;
DROP SEQUENCE FLEX_INDUSTRY_ID_SEQ;
DROP SEQUENCE FLEX_COMPANY_ID_SEQ;
DROP SEQUENCE FLEX_PRODUCT_SEQ;
DROP SEQUENCE FLEX_CONTACT_ID_SEQ;

commit;